update

diff --git a/S/COMMON b/S/COMMON
--- a/S/COMMON
+++ b/S/COMMON
@@ -13,11 +13,37 @@ getshpid()
 }
 error()
 {
-	echo "$prog: $1" >/dev/tty; exit "${2-1}"
+	echo "$prog: ${errormsg-}$1${errormsg2-}" >&2; exit "${2-1}"
 }
 is_empty()
 {
         awk 'NF {exit 1}' "$1"
+}
+head_except() ### head_except <-c|-v> <n> <file>
+{
+	head "$1" "$(("$(wc -l < "$3")" - "$2"))" "$3"
+}
+require()
+{
+	notfound()
+	{
+		errormsg="${errormsg-"error: need "}"
+		errormsg2="${errormsg2-", please check system environment"}"
+		error "${1-"$i"}"
+	}
+	for i in "$@"
+	do	case "$1" in
+		apk) apk -V || notfound;;
+		python) python -V || notfound;;
+		android|termux) [ "$in_termux" = 1 ] || notfound "android(termux) environment";;
+		python-*) modname="${i#python-}"; python -c import "$modname" || notfound "python module $modname";;
+		dir:*) [ -d "${i#dir:}" ] || notfound;;
+		file:*) [ -f "${i#file:}" ] || notfound;;
+		fsentry:*) [ -e "${i#fsentry:}" ] || notfound "file $i";;
+		cmd:*) type "${i#cmd:}" >/dev/null 2>&1 || notfound;;
+		*) errormsg="unknown requirement: " errormsg2= notfound;;
+		esac
+	done
 }
 
 [ "${TERMUX_VERSION+x}" ] && in_termux=1 || in_termux=0
diff --git a/S/banner b/S/banner
--- a/S/banner
+++ b/S/banner
@@ -2,13 +2,12 @@
 
 . "$(dirname "$0")/COMMON"
 
-## pipe to it
-calculate_length()( python3 -c 'import sys; from wcwidth import wcswidth; print(max(wcswidth(line[:-1]) for line in sys.stdin))' )
+require cmd:tput
 
-print_banner() ### var $variant
+print_banner() ### ( file )
 {
 	banner="$dir/BANNERS/$variant"
-	[ -f "$banner" ] || exit 1
+	[ -f "$banner" ] || error "banner file not found"
 	if [ "$(tput cols)" -ge "$(head -1 "$banner")" ]
 	then tail +3 "$banner"
 	else tail +2 "$banner" | head -1 ; repeat "$(tput cols)" '─'
@@ -18,15 +17,13 @@ print_banner() ### var $variant
 get_variant()
 {
 [ "$in_termux" = 1 ] && variant="termux" && return || :
-case "$(lsb_release -sc)" in
-chimera) variant="chimera";;
-alpine) variant="alpine";;
-*) variant="DEFAULT"
-esac
+variant="$("$dir/distinfo" ID)"
 }
 
 ## main
+
 ## variant override
 variant="${1-}"
 [ "$variant" ] || get_variant
-print_banner
+
+print_banner "$(get_variant)" || print_banner DEFAULT
diff --git a/S/rish b/S/rish
--- a/S/rish
+++ b/S/rish
@@ -1,25 +1,18 @@
-#!/system/bin/sh
-BASEDIR=$(dirname "$0")
-DEX="$BASEDIR"/rish_shizuku.dex
+#!/bin/sh -eu
 
-if [ ! -f "$DEX" ]; then
-  echo "Cannot find $DEX, please check the tutorial in Shizuku app"
-  exit 1
+. "$(dirname "$0")/COMMON"
+
+require android cmd:/system/bin/app_process
+
+### remade from shizuku's rish script
+
+dexfile="$dir/RES/rish_shizuku.dex"
+[ -f "$dexfile" ] || error "dexfile file not found, please put rish_shizuku.dexfile in $dir/RES/"
+
+if [ $(getprop ro.build.version.sdk) -ge 34 ]
+then	[ ! -w $dexfile ] || chmod a-w $dexfile
+	[ ! -w $dexfile ] || error "cannot chmod a-x $dexfilefile, please locate problem yourself"
 fi
 
-if [ $(getprop ro.build.version.sdk) -ge 34 ]; then
-  if [ -w $DEX ]; then
-    echo "On Android 14+, app_process cannot load writable dex."
-    echo "Attempting to remove the write permission..."
-    chmod 400 $DEX
-  fi
-  if [ -w $DEX ]; then
-    echo "Cannot remove the write permission of $DEX."
-    echo "You can copy to file to terminal app's private directory (/data/data/<package>, so that remove write permission is possible"
-    exit 1
-  fi
-fi
-
-# Replace "PKG" with the application id of your terminal app
-[ -z "$RISH_APPLICATION_ID" ] && export RISH_APPLICATION_ID="com.termux"
-/system/bin/app_process -Djava.class.path="$DEX" /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "$@"
+[ "${RISH_APPLICATION_ID-}" ] || export RISH_APPLICATION_ID="com.termux"
+/system/bin/app_process -Djava.class.path="$dexfile" /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "$@"
