update

diff --git a/S/hitokoto b/S/hitokoto
--- a/S/hitokoto
+++ b/S/hitokoto
@@ -1,5 +1,5 @@
-#!/data/data/com.termux/files/usr/bin/bash -eu
+#!/bin/sh -eu
 
 . "$(dirname "$0")/COMMON"
 
-curl --connect-timeout 0.6 --max-time 0.6 https://v1.hitokoto.cn?encode=text 2>/dev/null && echo || echo '无法连接至一言'
+curl --connect-timeout 0.6 --max-time 0.6 https://v1.hitokoto.cn?encode=text 2>/dev/null && echo || echo 'Cannot get hitokoto'
